//
// Created by GODPLC on 2020/5/22.
//

#ifndef UNTITLED1_FUNCTIONALOPERATION_H
#define UNTITLED1_FUNCTIONALOPERATION_H

void addNewWords();
void showAllWords();
#endif //UNTITLED1_FUNCTIONALOPERATION_H
